inherit_from:
  - ./.rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Exclude:
    - bin/**/*
    - db/**/*

Lint/EndAlignment:
  Enabled: true
  AlignWith: variable

Lint/HandleExceptions:
  Enabled: true
  StyleGuide: '#dont-hide-exceptions'
