language: ruby

sudo: false

rvm:
  - 2.3.0

cache: bundler

before_install:
  - gem install bundler

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/063c7f434dca5d9cb7ac

